apiVersion: v1
kind: Pod
metadata:
  name: nginx   #pod name
  labels:
    environment: dev
    project: roboshop
    purpose: poc
spec:
  containers:
    - name: nginx     #container name
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: almalinux  #container name
      image: almalinux:9
      command: ["sleep", "20"]