apiVersion: v1
kind: Pod
metadata:
  name: resources   #pod name
spec:
  containers:
    - name: nginx     #container name
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"